module.exports = {
  content: ['storyblok/**/*.{vue,js}', 'pages/**/*.vue'],
  safelist: [
    'bg-primary',
    'bg-secondary',
    'bg-tertiary',
    'bg-medium',
    'bg-dark',
    'bg-white',
    'bg-light',
    'hover:bg-primary',
    'hover:bg-secondary',
    'hover:bg-tertiary',
    'hover:bg-medium',
    'hover:bg-dark',
    'hover:bg-white',
    'hover:bg-light',
    'text-primary',
    'text-secondary',
    'text-tertiary',
    'text-medium',
    'text-dark',
    'text-white',
    'text-light',
    'hover:text-primary',
    'hover:text-secondary',
    'hover:text-tertiary',
    'hover:text-medium',
    'hover:text-dark',
    'hover:text-white',
    'hover:text-light',
    'border-primary',
    'border-secondary',
    'border-tertiary',
    'border-medium',
    'border-dark',
    'border-white',
    'border-light',
  ],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: '1rem',
        lg: '2rem',
      },
    },
    fontFamily: {
      sans: 'Oxygen, Outfit, sans-serif',
    },
    extend: {
      colors: {
        primary: '#437C90',
        primary_alt: '#2cafdc',
        //primary_alt: '#3794b4',
        secondary: '#D55672',
        tertiary: '#E8985E',
        light: '#f6f7f7',
        medium: '#bfc7c5',
        dark: '#152336',
      },
    },
  },
  plugins: [require('@tailwindcss/typography'), require('@tailwindcss/line-clamp')],
}
